# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_auto_20160116_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='nombre',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='mapa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articuloviaje',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nodo',
            name='tipo',
            field=models.CharField(choices=[('salida', 'Salida'), ('entrada', 'Entrada'), ('almacen', 'Almacen'), ('punto', 'Punto')], max_length=80),
        ),
        migrations.AlterField(
            model_name='robot',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('marcha', 'En Marcha'), ('fuera_de_servicio', 'Fuera de Servicio')], max_length=80),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='path',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
